services:
  base:
    build:
      #ruta a trav√©s de la cual desde cualquier proyecto
      #se tiene acceso a cualquier imagen (DFile), recurso
      context: /home/jose/devops/DespAW/Docker/Jose
      dockerfile: ./dockerfiles/base/ubuntu/Dockerfile
    container_name: ctbaseDAW